### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by ronalfy** [ronalfy/user-profile-picture#2]
@Monter I know this will be a bit of work, but I'd like to use language packs from now on. If you have time, can you please complete the language pack portion and then I'll remove the translation from the plugin file.

Otherwise, please let me know if you have no interest and I'll keep the Polish language file as-is.

At least with the language packs, it'll be independent of me releasing a new version with your updated translation.

https://translate.wordpress.org/locale/pl/default/wp-plugins/metronet-profile-picture

**Comment by Monter** [comment]
I'm sorry, but I do not understand what you mean. I made a full translation based on the POT file included with the plugin, I sent you a translated PO and MO files, you have added the files to the plugin. What's the problem? I don't use and don't have an account in wordpress.org

**Comment by ronalfy** [comment]
Not a problem. WordPress.org has official language packs that are
automatically downloaded if a language pack is complete.

The ultimate goal is to have languages removed from the plugin and have
them delivered from .org instead.

Seeing that you don't have a .org account, I'll leave your Polish
translation in the plugin.

If you decide to ultimately create a .org account and finish the
translation, that would be ideal in the long-term.

I'll go ahead and close out the issue. Thanks.

Ronald
