### ISSUE TITLE
Compatibilty for Profile picture of the author in AMP

### ISSUE THREAD

**Issue by ansaritalha** [ronalfy/user-profile-picture#9]
Made compatibility to display profile picture of the author of the post in amp version.

**Comment by ronalfy** [comment]
@ansaritalha I have added this functionality in the dev branch, but it needs testing.

I did install the AMP plugin and made sure it's working, but it wouldn't hurt for someone else to test it as well.

Thanks!

**Comment by ronalfy** [comment]
This issue is resolved.
